apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "proton-bridge.fullname" . }}
  labels:
    {{- include "proton-bridge.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "proton-bridge.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "proton-bridge.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "proton-bridge.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --non-interactive
          env:
            - name: BRIDGE_GPG_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "proton-bridge.fullname" . }}
                  key: bridgeGpgKey
          ports:
            - name: smtp
              containerPort: {{ .Values.service.smtp }}
              protocol: TCP
            - name: imap
              containerPort: {{ .Values.service.imap }}
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: smtp
            initialDelaySeconds: 30
            periodSeconds: 30
            failureThreshold: 10
          readinessProbe:
            tcpSocket:
              port: smtp
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: bridge-data
              mountPath: /root/.config/protonmail/bridge
              subPath: config
            - name: bridge-data
              mountPath: /root/.password-store
              subPath: password-store
            - name: bridge-data
              mountPath: /root/.cache/protonmail/bridge
              subPath: cache
      volumes:
        - name: bridge-data
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "proton-bridge.fullname" . }}
          {{- else }}
          emptyDir: {}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
