{{- if .Values.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "proton-bridge.fullname" . }}
  labels:
    {{- include "proton-bridge.labels" . | nindent 4 }}
type: Opaque
stringData:
  bridgeGpgKey: {{ .Values.secret.bridgeGpgKey | quote }}
{{- end }}
