remote_theme: pages-themes/cayman@v0.2.0
title: proton-bridge-agent
description: "Containerized proton-bridge for agents. Deployments via docker-compose and helm chart. IMAP/SMTP, and Discord notifications."
baseurl: /proton-bridge-agent
plugins:
  - jekyll-remote-theme
